# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# SEO
social:
  name: Souradeep Banerjee
  links:
  - "https://twitter.com/Souradeep1101"
  - "https://github.com/Souradeep1101"
  - "https://www.linkedin.com/in/Souradeep1101"
  - "https://instagram.com/souradeep_1101"
  - "https://www.reddit.com/user/Souradeep1101/"
  - "https://search.asu.edu/profile/4997799"
  - "https://www.youtube.com/channel/UCv4ctQjbqZ0tq8lxchYkm2g"
  - "https://www.facebook.com/profile.php?id=100081515016372"

# GitHub Settings
repository: Souradeep1101/portfolio

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Souradeep Banerjee
tagline: "Full-Stack Development • Video Generative AI • Machine Learning Research"
email: sbaner92@asu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Souradeep Banerjee's portfolio showcases full-stack web development, 
  video generative AI models, 
  and machine learning research projects.
twitter_username: Souradeep1101
github_username: Souradeep1101
minimal_mistakes_skin: neon
search: true
# search_provider: algolia
url: "https://souradeep.dev"
logo: "/assets/images/favicon/Logo _ Website - Dark.svg"
masthead_title: "\0"
breadcrumbs: true  # disabled by default

# Twitter
twitter:
  username: Souradeep1101    # your @handle, without the @
  card:    summary_large_image

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: "Souradeep Banerjee"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I'm Souradeep, a computer science student at Arizona State University dedicated to full-stack web development and leveraging generative AI to revolutionize anime production workflows."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://souradeep.dev"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Souradeep1101"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Souradeep1101"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/souradeep_1101"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/Souradeep1101"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/Souradeep1101/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCv4ctQjbqZ0tq8lxchYkm2g"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/profile.php?id=100081515016372"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Souradeep1101"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Souradeep1101"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/souradeep_1101"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/Souradeep1101"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/Souradeep1101/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCv4ctQjbqZ0tq8lxchYkm2g"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/profile.php?id=100081515016372"

# Hide Feed
atom_feed:
  hide: true

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-60NZ540GYT"
    anonymize_ip: false # default

# Google Site Verification
google_site_verification: "lKwlBHZdOo6032trFVsEXjkQVrlmgRo1qNkNbs2rEhA"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
  # _work
  - scope:
      path: ""
      type: work
    values:
      layout: single
      author_profile: true
      share: false
      classes: wide
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
      classes: wide

collections:
  work:
    output: true
    permalink: /work/:path/
  projects:
    output: true
    permalink: /projects/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
